#!/usr/bin/env bash
# Script to transfer a file to a server

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfer the file to the server's user home directory
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if the SCP command was successful
if [ "$?" -eq 0 ]; then
	echo "File transfer successful!"
else
	echo "File transfer failed!"
fi

