#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# Nginx should be listening on port 80
# Serve a page that returns the string "Hello World!"

set -e

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start nginx service
sudo service nginx start

# Allow nginx on firewall
if sudo ufw status | grep -q "Status: active"; then
    sudo ufw allow 'Nginx HTTP'
else
	echo "UFW is not active. Skipping firewall rule addition."
fi

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "<html>
  <head>
    <title>Welcome to nginx!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>" | sudo tee /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a YouTube video
sudo sed -i '/^ *location \/ {/a\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"

