#!/usr/bin/env bash
# Check if no arguments are provided
# Display usage instructions if no IP address is provided
# If an IP address is provided as an argument, execute ping command

if [ "$#" -eq 0 ]; then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
    ping -c 5 "$1"
fi
